import type { LucideIcon, LucideProps } from "lucide-react";
import {
  Target,
  BarChart3,
  Sparkles,
  Gift,
  MailCheck,
  ArrowRight,
  ArrowLeft,
  RotateCcw,
  Check,
  CheckCircle2,
  AlertTriangle,
  Lightbulb,
  Wallet,
  Brain,
  Anchor,
  Shield,
  BrickWall,
  Scale,
  Compass,
  Flame,
  Landmark,
  TrendingUp,
  TrendingDown,
  Rocket,
  CreditCard,
  Home,
  Frown,
  Meh,
  Smile,
  Laugh,
  Annoyed,
  Wine,
  Globe,
  Microscope,
  Footprints,
  CircleHelp,
  Dumbbell,
  Smartphone,
  Zap,
  Lock,
  Dices,
  Sprout,
} from "lucide-react";

export const ICON_MAP = {
  target: Target,
  "bar-chart": BarChart3,
  sparkles: Sparkles,
  gift: Gift,
  "mail-check": MailCheck,
  check: Check,
  "check-circle": CheckCircle2,
  "alert-triangle": AlertTriangle,
  lightbulb: Lightbulb,
  wallet: Wallet,
  brain: Brain,
  anchor: Anchor,
  shield: Shield,
  "brick-wall": BrickWall,
  scale: Scale,
  compass: Compass,
  flame: Flame,
  landmark: Landmark,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  rocket: Rocket,
  "credit-card": CreditCard,
  home: Home,
  frown: Frown,
  meh: Meh,
  smile: Smile,
  laugh: Laugh,
  annoyed: Annoyed,
  wine: Wine,
  globe: Globe,
  microscope: Microscope,
  footprints: Footprints,
  "circle-help": CircleHelp,
  dumbbell: Dumbbell,
  smartphone: Smartphone,
  zap: Zap,
  lock: Lock,
  dices: Dices,
  sprout: Sprout,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "rotate-ccw": RotateCcw,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_MAP;

export function DataIcon({
  name,
  ...props
}: { name: IconName } & Omit<LucideProps, "ref">) {
  const Icon = ICON_MAP[name];
  return <Icon {...props} />;
}
